In [30]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
import seaborn as sns
#ML classifiers
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import ShuffleSplit,cross_val_score
#ML evaluation metrics
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn import metrics, model_selection
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
#scikitplot to plot confusion matrix
import scikitplot as skplt

In [31]:
df_gender = pd.read_csv('gender-prediction.csv')
df_gender

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]

In [32]:
labels = preprocessing.LabelEncoder()

b_encoder = labels.fit_transform(df_gender.beard)
h_encoder = labels.fit_transform(df_gender.hair_length)
s_encoder = labels.fit_transform(df_gender.scarf)
e_encoder = labels.fit_transform(df_gender.eye_color)
g_encoder = labels.fit_transform(df_gender.gender)

In [33]:
#Q2) Apply Random Forest, Support Vector Machines, and Multilayer Perceptron classification algorithms(using Python) on the gender prediction dataset with standard train/test split ratio and answer the following questions.

In [34]:
#1. How many instances are incorrectly classified?
X = df_gender.drop('gender', axis=1)
y = df_gender['gender']

In [35]:
#Converting strings values into numbers

labels = preprocessing.LabelEncoder()
y_encoded = labels.fit_transform(y)
y_encoded

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0])

In [36]:
data = df_gender.drop(['beard','hair_length','scarf','eye_color','gender'],axis=1)
data

height  weight  shoe_size
0       71     176         44
1       68     165         41
2       62     132         37
3       65     138         38
4       70     197         43
..     ...     ...        ...
75      65      99         39
76      61      98         37
77      67     119         40
78      70     190         43
79      62     142         37

[80 rows x 3 columns]

In [37]:
X = list(zip(data.height, data.weight, b_encoder, h_encoder,data.shoe_size, s_encoder, e_encoder))
Y = g_encoder
X

[(71, 176, 1, 3, 44, 0, 0),
 (68, 165, 0, 0, 41, 0, 0),
 (62, 132, 0, 2, 37, 1, 1),
 (65, 138, 0, 1, 38, 0, 3),
 (70, 197, 1, 2, 43, 0, 3),
 (71, 190, 1, 3, 43, 0, 0),
 (74, 201, 1, 0, 44, 0, 2),
 (74, 182, 0, 3, 46, 0, 2),
 (63, 127, 0, 3, 35, 0, 4),
 (65, 139, 0, 2, 37, 1, 3),
 (66, 125, 0, 1, 36, 0, 3),
 (73, 188, 1, 3, 42, 0, 3),
 (74, 167, 0, 2, 41, 0, 0),
 (68, 141, 0, 1, 38, 0, 3),
 (70, 199, 1, 2, 40, 0, 0),
 (73, 189, 1, 3, 43, 0, 1),
 (69, 159, 0, 3, 43, 0, 0),
 (68, 135, 0, 1, 37, 1, 4),
 (68, 145, 0, 1, 38, 1, 3),
 (66, 138, 0, 2, 37, 0, 4),
 (66, 132, 0, 2, 40, 0, 0),
 (71, 170, 1, 2, 42, 0, 0),
 (67, 119, 1, 3, 40, 0, 0),
 (70, 190, 1, 2, 43, 0, 3),
 (68, 154, 0, 2, 38, 1, 2),
 (71, 155, 1, 2, 45, 0, 2),
 (69, 121, 1, 2, 41, 0, 0),
 (68, 97, 0, 2, 39, 0, 4),
 (68, 158, 0, 1, 38, 0, 1),
 (58, 92, 0, 3, 40, 1, 3),
 (63, 109, 0, 2, 37, 1, 2),
 (71, 158, 1, 2, 44, 0, 3),
 (61, 88, 0, 1, 37, 0, 3),
 (67, 132, 0, 2, 38, 0, 0),
 (62, 116, 0, 2, 39, 1, 2),
 (71, 125, 1, 2, 42, 0,

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.33, random_state = 2)

In [39]:
model= RandomForestClassifier()

In [40]:
model.fit(X_train,Y_train)

RandomForestClassifier()

In [41]:
prediction = model.predict(X_test)

In [42]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[10  0]
 [ 0 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        17

    accuracy                           1.00        27
   macro avg       1.00      1.00      1.00        27
weighted avg       1.00      1.00      1.00        27

100.0


In [43]:
model = SVC()

In [44]:
model.fit(X_train,Y_train)

SVC()

In [45]:
prediction = model.predict(X_test)

In [46]:
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

              precision    recall  f1-score   support

           0       0.70      0.70      0.70        10
           1       0.82      0.82      0.82        17

    accuracy                           0.78        27
   macro avg       0.76      0.76      0.76        27
weighted avg       0.78      0.78      0.78        27

[[ 7  3]
 [ 3 14]]
77.77777777777779


In [47]:
model = Perceptron()

In [48]:
model.fit(X_train,Y_train)

Perceptron()

In [49]:
prediction = model.predict(X_test)

In [50]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[ 9  1]
 [ 7 10]]
              precision    recall  f1-score   support

           0       0.56      0.90      0.69        10
           1       0.91      0.59      0.71        17

    accuracy                           0.70        27
   macro avg       0.74      0.74      0.70        27
weighted avg       0.78      0.70      0.71        27

70.37037037037037


In [51]:
#2. Rerun the experiment using train/test split ratio of 80/20. Do you see any change in the results? Explain.

In [52]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 2)

In [53]:
model= RandomForestClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [54]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[ 6  0]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16

100.0


In [55]:
model = SVC()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [56]:
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

              precision    recall  f1-score   support

           0       0.80      0.67      0.73         6
           1       0.82      0.90      0.86        10

    accuracy                           0.81        16
   macro avg       0.81      0.78      0.79        16
weighted avg       0.81      0.81      0.81        16

[[4 2]
 [1 9]]
81.25


In [57]:
model = Perceptron()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [58]:
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

              precision    recall  f1-score   support

           0       0.75      0.50      0.60         6
           1       0.75      0.90      0.82        10

    accuracy                           0.75        16
   macro avg       0.75      0.70      0.71        16
weighted avg       0.75      0.75      0.74        16

[[3 3]
 [1 9]]
75.0


In [59]:
#4. Try to exclude these 2 attribute(s) from the dataset. Rerun the experiment (using 80/20 train/test split), did you find any change in the results? Explain.

In [60]:
data = df_gender.drop(['beard','scarf','gender'],axis=1)
data

height  weight hair_length  shoe_size eye_color
0       71     176       short         44     black
1       68     165        bald         41     black
2       62     132      medium         37      blue
3       65     138        long         38      gray
4       70     197      medium         43      gray
..     ...     ...         ...        ...       ...
75      65      99       short         39     green
76      61      98       short         37     brown
77      67     119       short         40     black
78      70     190      medium         43      gray
79      62     142        long         37      blue

[80 rows x 5 columns]

In [61]:
X = list(zip(data.height, data.weight, h_encoder,data.shoe_size, e_encoder))
Y = g_encoder
X

[(71, 176, 3, 44, 0),
 (68, 165, 0, 41, 0),
 (62, 132, 2, 37, 1),
 (65, 138, 1, 38, 3),
 (70, 197, 2, 43, 3),
 (71, 190, 3, 43, 0),
 (74, 201, 0, 44, 2),
 (74, 182, 3, 46, 2),
 (63, 127, 3, 35, 4),
 (65, 139, 2, 37, 3),
 (66, 125, 1, 36, 3),
 (73, 188, 3, 42, 3),
 (74, 167, 2, 41, 0),
 (68, 141, 1, 38, 3),
 (70, 199, 2, 40, 0),
 (73, 189, 3, 43, 1),
 (69, 159, 3, 43, 0),
 (68, 135, 1, 37, 4),
 (68, 145, 1, 38, 3),
 (66, 138, 2, 37, 4),
 (66, 132, 2, 40, 0),
 (71, 170, 2, 42, 0),
 (67, 119, 3, 40, 0),
 (70, 190, 2, 43, 3),
 (68, 154, 2, 38, 2),
 (71, 155, 2, 45, 2),
 (69, 121, 2, 41, 0),
 (68, 97, 2, 39, 4),
 (68, 158, 1, 38, 1),
 (58, 92, 3, 40, 3),
 (63, 109, 2, 37, 2),
 (71, 158, 2, 44, 3),
 (61, 88, 1, 37, 3),
 (67, 132, 2, 38, 0),
 (62, 116, 2, 39, 2),
 (71, 125, 2, 42, 2),
 (63, 125, 2, 39, 4),
 (68, 121, 2, 40, 0),
 (67, 145, 1, 39, 3),
 (65, 99, 2, 38, 4),
 (61, 98, 3, 37, 3),
 (70, 167, 2, 42, 0),
 (64, 122, 2, 42, 0),
 (61, 156, 3, 41, 2),
 (69, 178, 0, 44, 0),
 (72, 150, 2, 4

In [62]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 2)

In [63]:
model= RandomForestClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [64]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[ 6  0]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16

100.0


In [65]:
model= SVC()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [66]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[4 2]
 [1 9]]
              precision    recall  f1-score   support

           0       0.80      0.67      0.73         6
           1       0.82      0.90      0.86        10

    accuracy                           0.81        16
   macro avg       0.81      0.78      0.79        16
weighted avg       0.81      0.81      0.81        16

81.25


In [67]:
model = Perceptron()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [68]:
model_cm = metrics.confusion_matrix(Y_test, prediction)
print(model_cm)
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

[[3 3]
 [1 9]]
              precision    recall  f1-score   support

           0       0.75      0.50      0.60         6
           1       0.75      0.90      0.82        10

    accuracy                           0.75        16
   macro avg       0.75      0.70      0.71        16
weighted avg       0.75      0.75      0.74        16

75.0


In [69]:
#Q3: Apply Decision Tree Classifier classification algorithm (using Python) on the gender prediction dataset with Monte Carlo cross-validation and Leave P-Out cross-validation. Report F1 score for both cross-validation strategies

In [70]:
#Leave P-Out cross-validation

In [71]:
model = DecisionTreeClassifier()

In [72]:
prediction = model_selection.cross_val_predict(model, X, y_encoded, cv=5)

In [73]:
model_fscore = f1_score(y_encoded, prediction)
print(model_fscore)

0.9473684210526316


In [74]:
#Monte Carlo cross-validation

In [75]:
model = DecisionTreeClassifier()

In [76]:
prediction = model_selection.cross_val_predict(model, X, y_encoded, cv=10)

In [77]:
model_fscore = f1_score(y_encoded, prediction)
print(model_fscore)

0.967741935483871


In [78]:
#Q4: Add 5 sample instances into the dataset (you can ask your friends/relatives/sibling for the data). Rerun the ML experiment (using Python) by training the model using Gaussian Naïve Bayes classification algorithmand all the instances from the gender prediction dataset. Evaluate the trained model using the newly added testinstances. Report accuracy, precision, and recall scores

In [89]:
df_gender = pd.read_csv('NewDataSet.csv')
df_gender

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
80      72     153   yes      medium         42    no     black    male
81      67     130   yes      medium         40    no     black    male
82      72     154   yes      medium         42    no     black    male
83      67     119   yes      medium         40    no     brown    male
84      65     160    no      medium         41    no     brown    male

[85 rows x 8 columns]

In [90]:
labels = preprocessing.LabelEncoder()

b_encoder = labels.fit_transform(df_gender.beard)
h_encoder = labels.fit_transform(df_gender.hair_length)
s_encoder = labels.fit_transform(df_gender.scarf)
e_encoder = labels.fit_transform(df_gender.eye_color)
g_encoder = labels.fit_transform(df_gender.gender)

In [91]:
labels = preprocessing.LabelEncoder()
y_encoded = labels.fit_transform(y)

In [92]:
data = df_gender.drop(['beard','hair_length','scarf','eye_color','gender'],axis=1)
data

height  weight  shoe_size
0       71     176         44
1       68     165         41
2       62     132         37
3       65     138         38
4       70     197         43
..     ...     ...        ...
80      72     153         42
81      67     130         40
82      72     154         42
83      67     119         40
84      65     160         41

[85 rows x 3 columns]

In [93]:
X = list(zip(data.height, data.weight, b_encoder, h_encoder,data.shoe_size, s_encoder, e_encoder))
Y = g_encoder
X

[(71, 176, 1, 3, 44, 0, 0),
 (68, 165, 0, 0, 41, 0, 0),
 (62, 132, 0, 2, 37, 1, 1),
 (65, 138, 0, 1, 38, 0, 3),
 (70, 197, 1, 2, 43, 0, 3),
 (71, 190, 1, 3, 43, 0, 0),
 (74, 201, 1, 0, 44, 0, 2),
 (74, 182, 0, 3, 46, 0, 2),
 (63, 127, 0, 3, 35, 0, 4),
 (65, 139, 0, 2, 37, 1, 3),
 (66, 125, 0, 1, 36, 0, 3),
 (73, 188, 1, 3, 42, 0, 3),
 (74, 167, 0, 2, 41, 0, 0),
 (68, 141, 0, 1, 38, 0, 3),
 (70, 199, 1, 2, 40, 0, 0),
 (73, 189, 1, 3, 43, 0, 1),
 (69, 159, 0, 3, 43, 0, 0),
 (68, 135, 0, 1, 37, 1, 4),
 (68, 145, 0, 1, 38, 1, 3),
 (66, 138, 0, 2, 37, 0, 4),
 (66, 132, 0, 2, 40, 0, 0),
 (71, 170, 1, 2, 42, 0, 0),
 (67, 119, 1, 3, 40, 0, 0),
 (70, 190, 1, 2, 43, 0, 3),
 (68, 154, 0, 2, 38, 1, 2),
 (71, 155, 1, 2, 45, 0, 2),
 (69, 121, 1, 2, 41, 0, 0),
 (68, 97, 0, 2, 39, 0, 4),
 (68, 158, 0, 1, 38, 0, 1),
 (58, 92, 0, 3, 40, 1, 3),
 (63, 109, 0, 2, 37, 1, 2),
 (71, 158, 1, 2, 44, 0, 3),
 (61, 88, 0, 1, 37, 0, 3),
 (67, 132, 0, 2, 38, 0, 0),
 (62, 116, 0, 2, 39, 1, 2),
 (71, 125, 1, 2, 42, 0,

In [94]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.33, random_state = 2)

In [95]:
model = GaussianNB()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)

In [96]:
model_acc = accuracy_score(Y_test, prediction)*100
print(model_acc)

93.10344827586206


In [97]:
model_precision = precision_score(Y_test,prediction)*100
print(model_precision)

90.0


In [98]:
model_recall = recall_score(Y_test,prediction)*100
print(model_recall)

100.0


In [99]:
model_cl_rep = metrics.classification_report(Y_test, prediction)
print(model_cl_rep)

              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.90      1.00      0.95        18

    accuracy                           0.93        29
   macro avg       0.95      0.91      0.92        29
weighted avg       0.94      0.93      0.93        29

